### ISSUE TITLE
[Suggestion] When config option "Hide JREI" is enabled, add a note somewhere indicating this config is enabled.

### ISSUE THREAD

**Issue by Gbergz** [SrRapero720/chloride#70] opened 2024-06-27 13:50 UTC
When config option "Hide JREI" is enabled, add a note somewhere indicating this option is enabled.
Maybe when hovering over the search bar or similar.

Would prevent some cases where people report JEI is malfunctioning while it technically isn't.

Thanks.

**Comment by SrRapero720** [comment] 2024-06-27 14:59
Duplicate of #69

**Closed as not planned by SrRapero720** 2024-06-27 14:59 UTC
